import { CountryMetadata } from "./types";

export const countryData: { [key: string]: CountryMetadata } = {
  Afghanistan: { flag: "🇦🇫", alpha2: "AF", alpha3: "AFG" },
  Albania: { flag: "🇦🇱", alpha2: "AL", alpha3: "ALB" },
  Algeria: { flag: "🇩🇿", alpha2: "DZ", alpha3: "DZA" },
  Andorra: { flag: "🇦🇩", alpha2: "AD", alpha3: "AND" },
  Angola: { flag: "🇦🇴", alpha2: "AO", alpha3: "AGO" },
  "Antigua and Barbuda": { flag: "🇦🇬", alpha2: "AG", alpha3: "ATG" },
  Argentina: { flag: "🇦🇷", alpha2: "AR", alpha3: "ARG" },
  Armenia: { flag: "🇦🇲", alpha2: "AM", alpha3: "ARM" },
  Australia: { flag: "🇦🇺", alpha2: "AU", alpha3: "AUS" },
  Austria: { flag: "🇦🇹", alpha2: "AT", alpha3: "AUT" },
  Azerbaijan: { flag: "🇦🇿", alpha2: "AZ", alpha3: "AZE" },
  Bahamas: { flag: "🇧🇸", alpha2: "BS", alpha3: "BHS" },
  Bahrain: { flag: "🇧🇭", alpha2: "BH", alpha3: "BHR" },
  Bangladesh: { flag: "🇧🇩", alpha2: "BD", alpha3: "BGD" },
  Barbados: { flag: "🇧🇧", alpha2: "BB", alpha3: "BRB" },
  Belarus: { flag: "🇧🇾", alpha2: "BY", alpha3: "BLR" },
  Belgium: { flag: "🇧🇪", alpha2: "BE", alpha3: "BEL" },
  Belize: { flag: "🇧🇿", alpha2: "BZ", alpha3: "BLZ" },
  Benin: { flag: "🇧🇯", alpha2: "BJ", alpha3: "BEN" },
  Bhutan: { flag: "🇧🇹", alpha2: "BT", alpha3: "BTN" },
  Bolivia: { flag: "🇧🇴", alpha2: "BO", alpha3: "BOL" },
  "Bosnia and Herzegovina": { flag: "🇧🇦", alpha2: "BA", alpha3: "BIH" },
  Botswana: { flag: "🇧🇼", alpha2: "BW", alpha3: "BWA" },
  Brazil: { flag: "🇧🇷", alpha2: "BR", alpha3: "BRA" },
  Brunei: { flag: "🇧🇳", alpha2: "BN", alpha3: "BRN" },
  Bulgaria: { flag: "🇧🇬", alpha2: "BG", alpha3: "BGR" },
  "Burkina Faso": { flag: "🇧🇫", alpha2: "BF", alpha3: "BFA" },
  Burundi: { flag: "🇧🇮", alpha2: "BI", alpha3: "BDI" },
  "Cabo Verde": { flag: "🇨🇻", alpha2: "CV", alpha3: "CPV" },
  Cambodia: { flag: "🇰🇭", alpha2: "KH", alpha3: "KHM" },
  Cameroon: { flag: "🇨🇲", alpha2: "CM", alpha3: "CMR" },
  Canada: { flag: "🇨🇦", alpha2: "CA", alpha3: "CAN" },
  "Central African Republic": { flag: "🇨🇫", alpha2: "CF", alpha3: "CAF" },
  Chad: { flag: "🇹🇩", alpha2: "TD", alpha3: "TCD" },
  Chile: { flag: "🇨🇱", alpha2: "CL", alpha3: "CHL" },
  China: { flag: "🇨🇳", alpha2: "CN", alpha3: "CHN" },
  Colombia: { flag: "🇨🇴", alpha2: "CO", alpha3: "COL" },
  Comoros: { flag: "🇰🇲", alpha2: "KM", alpha3: "COM" },
  "Congo (Congo-Brazzaville)": { flag: "🇨🇬", alpha2: "CG", alpha3: "COG" },
  "Congo (Democratic Republic)": { flag: "🇨🇩", alpha2: "CD", alpha3: "COD" },
  "Costa Rica": { flag: "🇨🇷", alpha2: "CR", alpha3: "CRI" },
  Croatia: { flag: "🇭🇷", alpha2: "HR", alpha3: "HRV" },
  Cuba: { flag: "🇨🇺", alpha2: "CU", alpha3: "CUB" },
  Cyprus: { flag: "🇨🇾", alpha2: "CY", alpha3: "CYP" },
  "Czech Republic": { flag: "🇨🇿", alpha2: "CZ", alpha3: "CZE" },
  Denmark: { flag: "🇩🇰", alpha2: "DK", alpha3: "DNK" },
  Djibouti: { flag: "🇩🇯", alpha2: "DJ", alpha3: "DJI" },
  Dominica: { flag: "🇩🇲", alpha2: "DM", alpha3: "DMA" },
  "Dominican Republic": { flag: "🇩🇴", alpha2: "DO", alpha3: "DOM" },
  Ecuador: { flag: "🇪🇨", alpha2: "EC", alpha3: "ECU" },
  Egypt: { flag: "🇪🇬", alpha2: "EG", alpha3: "EGY" },
  "El Salvador": { flag: "🇸🇻", alpha2: "SV", alpha3: "SLV" },
  "Equatorial Guinea": { flag: "🇬🇶", alpha2: "GQ", alpha3: "GNQ" },
  Eritrea: { flag: "🇪🇷", alpha2: "ER", alpha3: "ERI" },
  Estonia: { flag: "🇪🇪", alpha2: "EE", alpha3: "EST" },
  Eswatini: { flag: "🇸🇿", alpha2: "SZ", alpha3: "SWZ" },
  Ethiopia: { flag: "🇪🇹", alpha2: "ET", alpha3: "ETH" },
  Fiji: { flag: "🇫🇯", alpha2: "FJ", alpha3: "FJI" },
  Finland: { flag: "🇫🇮", alpha2: "FI", alpha3: "FIN" },
  France: { flag: "🇫🇷", alpha2: "FR", alpha3: "FRA" },
  Gabon: { flag: "🇬🇦", alpha2: "GA", alpha3: "GAB" },
  Gambia: { flag: "🇬🇲", alpha2: "GM", alpha3: "GMB" },
  Georgia: { flag: "🇬🇪", alpha2: "GE", alpha3: "GEO" },
  Germany: { flag: "🇩🇪", alpha2: "DE", alpha3: "DEU" },
  Ghana: { flag: "🇬🇭", alpha2: "GH", alpha3: "GHA" },
  Greece: { flag: "🇬🇷", alpha2: "GR", alpha3: "GRC" },
  Grenada: { flag: "🇬🇩", alpha2: "GD", alpha3: "GRD" },
  Guatemala: { flag: "🇬🇹", alpha2: "GT", alpha3: "GTM" },
  Guinea: { flag: "🇬🇳", alpha2: "GN", alpha3: "GIN" },
  "Guinea-Bissau": { flag: "🇬🇼", alpha2: "GW", alpha3: "GNB" },
  Guyana: { flag: "🇬🇾", alpha2: "GY", alpha3: "GUY" },
  Haiti: { flag: "🇭🇹", alpha2: "HT", alpha3: "HTI" },
  Honduras: { flag: "🇭🇳", alpha2: "HN", alpha3: "HND" },
  Hungary: { flag: "🇭🇺", alpha2: "HU", alpha3: "HUN" },
  Iceland: { flag: "🇮🇸", alpha2: "IS", alpha3: "ISL" },
  India: { flag: "🇮🇳", alpha2: "IN", alpha3: "IND" },
  Indonesia: { flag: "🇮🇩", alpha2: "ID", alpha3: "IDN" },
  Iran: { flag: "🇮🇷", alpha2: "IR", alpha3: "IRN" },
  Iraq: { flag: "🇮🇶", alpha2: "IQ", alpha3: "IRQ" },
  Ireland: { flag: "🇮🇪", alpha2: "IE", alpha3: "IRL" },
  Israel: { flag: "🇮🇱", alpha2: "IL", alpha3: "ISR" },
  Italy: { flag: "🇮🇹", alpha2: "IT", alpha3: "ITA" },
  Jamaica: { flag: "🇯🇲", alpha2: "JM", alpha3: "JAM" },
  Japan: { flag: "🇯🇵", alpha2: "JP", alpha3: "JPN" },
  Jordan: { flag: "🇯🇴", alpha2: "JO", alpha3: "JOR" },
  Kazakhstan: { flag: "🇰🇿", alpha2: "KZ", alpha3: "KAZ" },
  Kenya: { flag: "🇰🇪", alpha2: "KE", alpha3: "KEN" },
  Kiribati: { flag: "🇰🇮", alpha2: "KI", alpha3: "KIR" },
  Kuwait: { flag: "🇰🇼", alpha2: "KW", alpha3: "KWT" },
  Kyrgyzstan: { flag: "🇰🇬", alpha2: "KG", alpha3: "KGZ" },
  Laos: { flag: "🇱🇦", alpha2: "LA", alpha3: "LAO" },
  Latvia: { flag: "🇱🇻", alpha2: "LV", alpha3: "LVA" },
  Lebanon: { flag: "🇱🇧", alpha2: "LB", alpha3: "LBN" },
  Lesotho: { flag: "🇱🇸", alpha2: "LS", alpha3: "LSO" },
  Liberia: { flag: "🇱🇷", alpha2: "LR", alpha3: "LBR" },
  Libya: { flag: "🇱🇾", alpha2: "LY", alpha3: "LBY" },
  Liechtenstein: { flag: "🇱🇮", alpha2: "LI", alpha3: "LIE" },
  Lithuania: { flag: "🇱🇹", alpha2: "LT", alpha3: "LTU" },
  Luxembourg: { flag: "🇱🇺", alpha2: "LU", alpha3: "LUX" },
  Madagascar: { flag: "🇲🇬", alpha2: "MG", alpha3: "MDG" },
  Malawi: { flag: "🇲🇼", alpha2: "MW", alpha3: "MWI" },
  Malaysia: { flag: "🇲🇾", alpha2: "MY", alpha3: "MYS" },
  Maldives: { flag: "🇲🇻", alpha2: "MV", alpha3: "MDV" },
  Mali: { flag: "🇲🇱", alpha2: "ML", alpha3: "MLI" },
  Malta: { flag: "🇲🇹", alpha2: "MT", alpha3: "MLT" },
  "Marshall Islands": { flag: "🇲🇭", alpha2: "MH", alpha3: "MHL" },
  Mauritania: { flag: "🇲🇷", alpha2: "MR", alpha3: "MRT" },
  Mauritius: { flag: "🇲🇺", alpha2: "MU", alpha3: "MUS" },
  Mexico: { flag: "🇲🇽", alpha2: "MX", alpha3: "MEX" },
  Micronesia: { flag: "🇫🇲", alpha2: "FM", alpha3: "FSM" },
  Moldova: { flag: "🇲🇩", alpha2: "MD", alpha3: "MDA" },
  Monaco: { flag: "🇲🇨", alpha2: "MC", alpha3: "MCO" },
  Mongolia: { flag: "🇲🇳", alpha2: "MN", alpha3: "MNG" },
  Montenegro: { flag: "🇲🇪", alpha2: "ME", alpha3: "MNE" },
  Morocco: { flag: "🇲🇦", alpha2: "MA", alpha3: "MAR" },
  Mozambique: { flag: "🇲🇿", alpha2: "MZ", alpha3: "MOZ" },
  "Myanmar (Burma)": { flag: "🇲🇲", alpha2: "MM", alpha3: "MMR" },
  Namibia: { flag: "🇳🇦", alpha2: "NA", alpha3: "NAM" },
  Nauru: { flag: "🇳🇷", alpha2: "NR", alpha3: "NRU" },
  Nepal: { flag: "🇳🇵", alpha2: "NP", alpha3: "NPL" },
  Netherlands: { flag: "🇳🇱", alpha2: "NL", alpha3: "NLD" },
  "New Zealand": { flag: "🇳🇿", alpha2: "NZ", alpha3: "NZL" },
  Nicaragua: { flag: "🇳🇮", alpha2: "NI", alpha3: "NIC" },
  Niger: { flag: "🇳🇪", alpha2: "NE", alpha3: "NER" },
  Nigeria: { flag: "🇳🇬", alpha2: "NG", alpha3: "NGA" },
  "North Korea": { flag: "🇰🇵", alpha2: "KP", alpha3: "PRK" },
  "North Macedonia": { flag: "🇲🇰", alpha2: "MK", alpha3: "MKD" },
  Norway: { flag: "🇳🇴", alpha2: "NO", alpha3: "NOR" },
  Oman: { flag: "🇴🇲", alpha2: "OM", alpha3: "OMN" },
  Pakistan: { flag: "🇵🇰", alpha2: "PK", alpha3: "PAK" },
  Palau: { flag: "🇵🇼", alpha2: "PW", alpha3: "PLW" },
  Palestine: { flag: "🇵🇸", alpha2: "PS", alpha3: "PSE" },
  Panama: { flag: "🇵🇦", alpha2: "PA", alpha3: "PAN" },
  "Papua New Guinea": { flag: "🇵🇬", alpha2: "PG", alpha3: "PNG" },
  Paraguay: { flag: "🇵🇾", alpha2: "PY", alpha3: "PRY" },
  Peru: { flag: "🇵🇪", alpha2: "PE", alpha3: "PER" },
  Philippines: { flag: "🇵🇭", alpha2: "PH", alpha3: "PHL" },
  Poland: { flag: "🇵🇱", alpha2: "PL", alpha3: "POL" },
  Portugal: { flag: "🇵🇹", alpha2: "PT", alpha3: "PRT" },
  Qatar: { flag: "🇶🇦", alpha2: "QA", alpha3: "QAT" },
  Romania: { flag: "🇷🇴", alpha2: "RO", alpha3: "ROU" },
  Russia: { flag: "🇷🇺", alpha2: "RU", alpha3: "RUS" },
  Rwanda: { flag: "🇷🇼", alpha2: "RW", alpha3: "RWA" },
  "Saint Kitts and Nevis": { flag: "🇰🇳", alpha2: "KN", alpha3: "KNA" },
  "Saint Lucia": { flag: "🇱🇨", alpha2: "LC", alpha3: "LCA" },
  "Saint Vincent and the Grenadines": {
    flag: "🇻🇨",
    alpha2: "VC",
    alpha3: "VCT",
  },
  Samoa: { flag: "🇼🇸", alpha2: "WS", alpha3: "WSM" },
  "San Marino": { flag: "🇸🇲", alpha2: "SM", alpha3: "SMR" },
  "Sao Tome and Principe": { flag: "🇸🇹", alpha2: "ST", alpha3: "STP" },
  "Saudi Arabia": { flag: "🇸🇦", alpha2: "SA", alpha3: "SAU" },
  Senegal: { flag: "🇸🇳", alpha2: "SN", alpha3: "SEN" },
  Serbia: { flag: "🇷🇸", alpha2: "RS", alpha3: "SRB" },
  Seychelles: { flag: "🇸🇨", alpha2: "SC", alpha3: "SYC" },
  "Sierra Leone": { flag: "🇸🇱", alpha2: "SL", alpha3: "SLE" },
  Singapore: { flag: "🇸🇬", alpha2: "SG", alpha3: "SGP" },
  Slovakia: { flag: "🇸🇰", alpha2: "SK", alpha3: "SVK" },
  Slovenia: { flag: "🇸🇮", alpha2: "SI", alpha3: "SVN" },
  "Solomon Islands": { flag: "🇸🇧", alpha2: "SB", alpha3: "SLB" },
  Somalia: { flag: "🇸🇴", alpha2: "SO", alpha3: "SOM" },
  "South Africa": { flag: "🇿🇦", alpha2: "ZA", alpha3: "ZAF" },
  "South Korea": { flag: "🇰🇷", alpha2: "KR", alpha3: "KOR" },
  "South Sudan": { flag: "🇸🇸", alpha2: "SS", alpha3: "SSD" },
  Spain: { flag: "🇪🇸", alpha2: "ES", alpha3: "ESP" },
  "Sri Lanka": { flag: "🇱🇰", alpha2: "LK", alpha3: "LKA" },
  Sudan: { flag: "🇸🇩", alpha2: "SD", alpha3: "SDN" },
  Suriname: { flag: "🇸🇷", alpha2: "SR", alpha3: "SUR" },
  Sweden: { flag: "🇸🇪", alpha2: "SE", alpha3: "SWE" },
  Switzerland: { flag: "🇨🇭", alpha2: "CH", alpha3: "CHE" },
  Syria: { flag: "🇸🇾", alpha2: "SY", alpha3: "SYR" },
  Taiwan: { flag: "🇹🇼", alpha2: "TW", alpha3: "TWN" },
  Tajikistan: { flag: "🇹🇯", alpha2: "TJ", alpha3: "TJK" },
  Tanzania: { flag: "🇹🇿", alpha2: "TZ", alpha3: "TZA" },
  Thailand: { flag: "🇹🇭", alpha2: "TH", alpha3: "THA" },
  "Timor-Leste": { flag: "🇹🇱", alpha2: "TL", alpha3: "TLS" },
  Togo: { flag: "🇹🇬", alpha2: "TG", alpha3: "TGO" },
  Tonga: { flag: "🇹🇴", alpha2: "TO", alpha3: "TON" },
  "Trinidad and Tobago": { flag: "🇹🇹", alpha2: "TT", alpha3: "TTO" },
  Tunisia: { flag: "🇹🇳", alpha2: "TN", alpha3: "TUN" },
  Turkey: { flag: "🇹🇷", alpha2: "TR", alpha3: "TUR" },
  Turkmenistan: { flag: "🇹🇲", alpha2: "TM", alpha3: "TKM" },
  Tuvalu: { flag: "🇹🇻", alpha2: "TV", alpha3: "TUV" },
  Uganda: { flag: "🇺🇬", alpha2: "UG", alpha3: "UGA" },
  Ukraine: { flag: "🇺🇦", alpha2: "UA", alpha3: "UKR" },
  "United Arab Emirates": { flag: "🇦🇪", alpha2: "AE", alpha3: "ARE" },
  "United Kingdom": { flag: "🇬🇧", alpha2: "GB", alpha3: "GBR" },
  "United States": { flag: "🇺🇸", alpha2: "US", alpha3: "USA" },
  Uruguay: { flag: "🇺🇾", alpha2: "UY", alpha3: "URY" },
  Uzbekistan: { flag: "🇺🇿", alpha2: "UZ", alpha3: "UZB" },
  Vanuatu: { flag: "🇻🇺", alpha2: "VU", alpha3: "VUT" },
  "Vatican City": { flag: "🇻🇦", alpha2: "VA", alpha3: "VAT" },
  Venezuela: { flag: "🇻🇪", alpha2: "VE", alpha3: "VEN" },
  Vietnam: { flag: "🇻🇳", alpha2: "VN", alpha3: "VNM" },
  Yemen: { flag: "🇾🇪", alpha2: "YE", alpha3: "YEM" },
  Zambia: { flag: "🇿🇲", alpha2: "ZM", alpha3: "ZMB" },
  Zimbabwe: { flag: "🇿🇼", alpha2: "ZW", alpha3: "ZWE" },
};
